resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'

data_file 'DLC_ITYP_REQUEST' 'stream/slbBuildings/def_props.ytyp'

this_is_a_map 'yes'

files {
    "vehicleaihandlinginfo.meta",
    "handling.meta",
    "carcols.meta",
    'stream/detector/xm_detector_t.ytd',
    'stream/detector/xm_detector.ydr',
    'stream/detector/xm_detector_p.ytyp',
    'stream/detector/xm_detector_p.ymap',
    'stream/detector/xm_detector_c.ybn',
    'stream/detector/xm_prop_x17_tv_wall.yft',
    'peds.meta',
    'stream/slbBuildings/def_props.ytyp',
'stream/slbBuildings/slb2k11_court_small.ydr',
'stream/slbBuildings/slb2k11_art_01.ydr',
'stream/slbBuildings/slb2k11_art_02.ydr',
'stream/slbBuildings/slb2k11_art_03.ydr',
'stream/slbBuildings/slb2k11_art_04.ydr',
'stream/slbBuildings/slb2k11_art_05.ydr',
'stream/slbBuildings/slb2k11_art_06.ydr',
'stream/slbBuildings/slb2k11_art_m_01.ydr',
'stream/slbBuildings/slb2k11_art_m_02.ydr',    
'stream/slbBuildings/slb2k11_art_m_03.ydr',
'stream/slbBuildings/slb2k11_bed_head.ydr',
'stream/slbBuildings/slb2k11_bed1.ydr',
'stream/slbBuildings/slb2k11_bed2.ydr',
'stream/slbBuildings/slb2k11_bedtable.ydr',
'stream/slbBuildings/slb2k11_bench1.ydr',
'stream/slbBuildings/slb2k11_bench2.ydr',
'stream/slbBuildings/slb2k11_blackjack.ydr',
'stream/slbBuildings/slb2k11_boden_2x2.ydr',
'stream/slbBuildings/slb2k11_boden_2x2_1.ydr',
'stream/slbBuildings/slb2k11_boden_5x5.ydr',
'stream/slbBuildings/slb2k11_boden_5x5_2.ydr',
'stream/slbBuildings/slb2k11_boden_5x5_3.ydr',
'stream/slbBuildings/slb2k11_boden_5x5_4.ydr',
'stream/slbBuildings/slb2k11_boden_5x5_5.ydr',
'stream/slbBuildings/slb2k11_boden_10x10.ydr',
'stream/slbBuildings/slb2k11_boden_10x10_2.ydr',
'stream/slbBuildings/slb2k11_boden_10x10_3.ydr',
'stream/slbBuildings/slb2k11_casino_base.ydr',
'stream/slbBuildings/slb2k11_casino_base_2.ydr',
'stream/slbBuildings/slb2k11_casino_chair_01.ydr',
'stream/slbBuildings/slb2k11_casino_chair_02.ydr',
'stream/slbBuildings/slb2k11_casino_das_ding.ydr',
'stream/slbBuildings/slb2k11_casino_light.ydr',
'stream/slbBuildings/slb2k11_casino_roulette_2.ydr',
'stream/slbBuildings/slb2k11_casino_shadow.ydr',
'stream/slbBuildings/slb2k11_casino_spot.ydr',
'stream/slbBuildings/slb2k11_casino_spot_treppe.ydr',
'stream/slbBuildings/slb2k11_casino_stuff.ydr',
'stream/slbBuildings/slb2k11_casino_stuff_2.ydr',
'stream/slbBuildings/slb2k11_casino_stuff_3.ydr',
'stream/slbBuildings/slb2k11_casino_stuff_4.ydr',
'stream/slbBuildings/slb2k11_casino_stuff_5.ydr',
'stream/slbBuildings/slb2k11_casino_wc_1.ydr',
'stream/slbBuildings/slb2k11_casino_wc_2.ydr',
'stream/slbBuildings/slb2k11_casino_wc_3.ydr',
'stream/slbBuildings/slb2k11_casino_wc_4.ydr',
'stream/slbBuildings/slb2k11_cell_sign_1.ydr',
'stream/slbBuildings/slb2k11_cheffarzt.ydr',
'stream/slbBuildings/slb2k11_deko_jeton_500.ydr',
'stream/slbBuildings/slb2k11_deko_jeton_1000.ydr',
'stream/slbBuildings/slb2k11_deko_jeton_10000.ydr',
'stream/slbBuildings/slb2k11_emptybed.ydr',
'stream/slbBuildings/slb2k11_floor_2x2.ydr',
'stream/slbBuildings/slb2k11_fridge.ydr',
'stream/slbBuildings/slb2k11_gastank.ydr',
'stream/slbBuildings/slb2k11_Jail.ydr',
'stream/slbBuildings/slb2k11_jail_2.ydr',
'stream/slbBuildings/slb2k11_jeton_3x25.ydr',
'stream/slbBuildings/slb2k11_jeton_4x25.ydr',
'stream/slbBuildings/slb2k11_jeton_5x25.ydr',
'stream/slbBuildings/slb2k11_jeton_6x25.ydr',
'stream/slbBuildings/slb2k11_jeton_7x25.ydr',
'stream/slbBuildings/slb2k11_jeton_8x25.ydr',
'stream/slbBuildings/slb2k11_jeton_9x25.ydr',
'stream/slbBuildings/slb2k11_jeton_10x25.ydr',
'stream/slbBuildings/slb2k11_jeton_25.ydr',
'stream/slbBuildings/slb2k11_jeton_50.ydr',
'stream/slbBuildings/slb2k11_jeton_100.ydr',
'stream/slbBuildings/slb2k11_jeton_500.ydr',
'stream/slbBuildings/slb2k11_jeton_1000.ydr',
'stream/slbBuildings/slb2k11_jeton_10000.ydr',
'stream/slbBuildings/slb2k11_lamp_poker.ydr',
'stream/slbBuildings/slb2k11_largecupboard.ydr',
'stream/slbBuildings/slb2k11_largecupboard+hidr.ytd',
'stream/slbBuildings/slb2k11_light_green.ydr',
'stream/slbBuildings/slb2k11_light_red.ydr',
'stream/slbBuildings/slb2k11_lightbox.ydr',
'stream/slbBuildings/slb2k11_medstool.ydr',
'stream/slbBuildings/slb2k11_medwastebin.ydr',
'stream/slbBuildings/slb2k11_metalfume.ydr',
'stream/slbBuildings/slb2k11_minifridge.ydr',
'stream/slbBuildings/slb2k11_minifridge+hidr.ytd',
'stream/slbBuildings/slb2k11_mirror.ydr',
'stream/slbBuildings/slb2k11_photocopy.ydr',
'stream/slbBuildings/slb2k11_photocopy+hidr.ytd',
'stream/slbBuildings/slb2k11_pillar_casino.ydr',
'stream/slbBuildings/slb2k11_pillar2_casino.ydr',
'stream/slbBuildings/slb2k11_pokertable.ydr',
'stream/slbBuildings/slb2k11_pokertisch.ydr',
'stream/slbBuildings/slb2k11_roof_2x2.ydr',
'stream/slbBuildings/slb2k11_roof_2x2_1.ydr',
'stream/slbBuildings/slb2k11_roof_5x5.ydr',
'stream/slbBuildings/slb2k11_roulette.ydr',
'stream/slbBuildings/slb2k11_roulette_part.ydr',
'stream/slbBuildings/slb2k11_sidetable.ydr',
'stream/slbBuildings/slb2k11_sink.ydr',
'stream/slbBuildings/slb2k11_slot_table.ydr',
'stream/slbBuildings/slb2k11_slotmachine1.ydr',
'stream/slbBuildings/slb2k11_slotmachine2.ydr',
'stream/slbBuildings/slb2k11_slotmachine3.ydr',
'stream/slbBuildings/slb2k11_slotmachine4.ydr',
'stream/slbBuildings/slb2k11_stack_150.ydr',
'stream/slbBuildings/slb2k11_stack_300.ydr',
'stream/slbBuildings/slb2k11_stack_750.ydr',
'stream/slbBuildings/slb2k11_stack_2000.ydr',
'stream/slbBuildings/slb2k11_stack_4000.ydr',
'stream/slbBuildings/slb2k11_stack_9000.ydr',
'stream/slbBuildings/slb2k11_table_big.ydr',
'stream/slbBuildings/slb2k11_table_small.ydr',
'stream/slbBuildings/slb2k11_traverse_1.ydr',
'stream/slbBuildings/slb2k11_traverse_2.ydr',
'stream/slbBuildings/slb2k11_traverse_3.ydr',
'stream/slbBuildings/slb2k11_traverse_4.ydr',
'stream/slbBuildings/slb2k11_traverse_5.ydr',
'stream/slbBuildings/slb2k11_traverse_6.ydr',
'stream/slbBuildings/slb2k11_traverse_set.ydr',
'stream/slbBuildings/slb2k11_trolley.ydr',
'stream/slbBuildings/slb2k11_trolley2.ydr',
'stream/slbBuildings/slb2k11_trolley2+hidr.ytd',
'stream/slbBuildings/slb2k11_unita.ydr',
'stream/slbBuildings/slb2k11_wall_2x2_1.ydr',
'stream/slbBuildings/slb2k11_wall_2x2_2.ydr',
'stream/slbBuildings/slb2k11_wall_5x5.ydr',
'stream/slbBuildings/slb2k11_wallcab.ydr',
'stream/slbBuildings/slb2k11_wallunita.ydr',
'stream/slbBuildings/slb2k11_wallunita+hidr.ytd',
'stream/slbBuildings/slb2k11_wallunitb.ydr',
'stream/slbBuildings/slb2k11_wallunitb+hidr.ytd',
'stream/slbBuildings/slb2k11_wheelbench.ydr',
'stream/slbBuildings/textures.ytd',
'popgroups.ymt',
'mp_m_freemode_01_np_shop.meta',
'mp_f_freemode_01_np_shop.meta'

		--'ambientpedmodelsets.meta',
		--'vehiclemodelsets.meta',
		--'popcycle.dat',
}

data_file 'PED_METADATA_FILE' 'peds.meta'
data_file "VEHICLEAIHANDLINGINFO_FILE" "vehicleaihandlinginfo.meta"
data_file "HANDLING_FILE" "handling.meta"
data_file 'CARCOLS_FILE' 'carcols.meta'
data_file 'FIVEM_LOVES_YOU_341B23A2F0E0F131' 'popgroups.ymt'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_m_freemode_01_np_shop.meta'
data_file 'SHOP_PED_APPAREL_META_FILE' 'mp_f_freemode_01_np_shop.meta'
		
		--data_file 'AMBIENT_PED_MODEL_SET_FILE' 'ambientpedmodelsets.meta'
		--data_file 'AMBIENT_VEHICLE_MODEL_SET_FILE' 'vehiclemodelsets.meta'
		--data_file 'POPSCHED_FILE' 'popcycle.dat'
